#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/kafka_demo
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

ibm.mq.queue-manager=QM1
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.conn-name=localhost(1414)
ibm.mq.user=app
ibm.mq.password=passw0rd
ibm.mq.queue=NOTIFICATION.Q
ibm.mq.dead-letter-queue=DEAD.LETTER.QUEUE
ibm.mq.ccdt-url=
ibm.mq.ssl-cipher-suite=
spring.jms.listener.session-transacted=true
logging.level.com.ibm.mq=DEBUG
logging.level.org.springframework.jms=DEBUG
